spring.datasource.url=jdbc:h2:file:./data/rail-sandbox;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
server.port=5215
spring.jackson.default-property-inclusion=non_null
