CREATE TABLE IF NOT EXISTS raw_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evidence_kind VARCHAR(32) NOT NULL,
  evidence_key VARCHAR(128) NOT NULL,
  received_at VARCHAR(40) NOT NULL,
  received_from VARCHAR(255) NOT NULL,
  payload CLOB NOT NULL,
  source_fingerprint CHAR(64) NOT NULL,
  UNIQUE(evidence_kind, source_fingerprint)
);

CREATE TABLE IF NOT EXISTS topology_revisions (
  revision_id VARCHAR(128) PRIMARY KEY,
  evidence_id BIGINT NOT NULL,
  base_revision_id VARCHAR(128),
  version_number INTEGER NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  topology_id VARCHAR(128) NOT NULL,
  payload CLOB NOT NULL,
  source_fingerprint CHAR(64) NOT NULL,
  rule_fingerprint CHAR(64),
  UNIQUE(version_number, topology_id)
);

CREATE TABLE IF NOT EXISTS rule_revisions (
  revision_id VARCHAR(128) PRIMARY KEY,
  evidence_id BIGINT NOT NULL,
  base_revision_id VARCHAR(128),
  version_number INTEGER NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  rule_id VARCHAR(128) NOT NULL,
  payload CLOB NOT NULL,
  source_fingerprint CHAR(64) NOT NULL,
  UNIQUE(version_number, rule_id)
);

CREATE TABLE IF NOT EXISTS scenario_revisions (
  revision_id VARCHAR(128) PRIMARY KEY,
  evidence_id BIGINT NOT NULL,
  base_revision_id VARCHAR(128),
  version_number INTEGER NOT NULL,
  created_at VARCHAR(40) NOT NULL,
  scenario_id VARCHAR(128) NOT NULL,
  payload CLOB NOT NULL,
  source_fingerprint CHAR(64) NOT NULL,
  topology_fingerprint CHAR(64),
  rule_fingerprint CHAR(64),
  fault_of_revision_id VARCHAR(128),
  UNIQUE(version_number, scenario_id)
);

CREATE TABLE IF NOT EXISTS approvals (
  approval_id VARCHAR(128) PRIMARY KEY,
  approved_at VARCHAR(40) NOT NULL,
  topology_revision_id VARCHAR(128) NOT NULL,
  rule_revision_id VARCHAR(128) NOT NULL,
  scenario_revision_id VARCHAR(128) NOT NULL,
  topology_fingerprint CHAR(64) NOT NULL,
  rule_fingerprint CHAR(64) NOT NULL,
  scenario_fingerprint CHAR(64) NOT NULL,
  package_fingerprint CHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS verification_runs (
  run_id VARCHAR(128) PRIMARY KEY,
  created_at VARCHAR(40) NOT NULL,
  approval_id VARCHAR(128),
  topology_revision_id VARCHAR(128) NOT NULL,
  rule_revision_id VARCHAR(128) NOT NULL,
  scenario_revision_id VARCHAR(128) NOT NULL,
  candidate_rule_revision_id VARCHAR(128),
  max_depth INTEGER NOT NULL,
  max_states INTEGER NOT NULL,
  report CLOB NOT NULL,
  report_fingerprint CHAR(64) NOT NULL
);
